services:
  control-connector:
    container_name: control-connector
    build: ../spiking-control-connector/
    image: "louisross/spiking-model-control-connector:1.1"
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - "../spiking-model-configuration/configuration/:/configuration"
  initializer-shim:
    container_name: initializer-shim
    build: ../spiking-initializer-shim/
    image: "louisross/spiking-initializer-shim:1.0"
    ports:
      - 4000:4000
    volumes:
      - "../spiking-model-configuration/configuration/:/configuration"
  realtime-shim:
    container_name: realtime-shim
    build: ../spiking-realtime-shim/
    image: "louisross/spiking-realtime-shim:1.0"
    ports:
      - 4001:4000
      - 5003:5000
    volumes:
      - "../spiking-model-configuration/configuration/:/configuration"
  model-persist:
    container_name: model-persist
    build: ../spiking-model-persist/backend/
    image: "louisross/spiking-model-persist-backend:1.0"
    volumes:
      - "../spiking-model-persist/h5:/data"
      - "../spiking-model-configuration/configuration/:/configuration"
    ports:
      - 5002:5000
  model-packager:
    container_name: model-packager
    build: ../spiking-model-packager/
    image: "louisross/spiking-model-packager:1.0"
    ports:
      - 5004:5000
    volumes:
      - "../spiking-model-configuration/configuration/:/configuration"
      - "../spiking-model-configuration/configuration/utils/:/usr/src/app/utils"
      - "/media/louis/Elements/spiking-model-templates/:/templates"
    depends_on:
      - model-persist
  model-control:
    container_name: model-control
    build: ../spiking-model-control/
    image: "louisross/spiking-model-control:1.0"
    ports:
      - 8081:3000
    volumes:
      - "../spiking-model-configuration/configuration/:/app/src/configfiles"
#      - "../spiking-model-configuration/src/:/app/src/configuration"
    depends_on:
      - control-connector
  model-monitor:
    container_name: model-monitor
    build: ../spiking-model-monitor/
    image: "louisross/spiking-model-monitor:1.0"
    ports:
      - 8082:3000
    volumes:
      - "../spiking-model-configuration/configuration/:/app/src/configfiles"
      - "../spiking-model-configuration/src/:/app/src/configuration"
    depends_on:
      - model-packager
      - realtime-shim
  model-selector:
    container_name: model-selector
    build: "./"
    image: "louisross/spiking-model-selector:1.0"
    ports:
      - 8080:3000
    volumes:
      - "../spiking-model-configuration/configuration/:/app/src/configfiles"
      - "../spiking-model-configuration/src/:/app/src/configuration"
    depends_on:
      - model-control
      - model-monitor
